- new_homepage_src/_user_guide/010_installation.md
- new_homepage_src/quick_start.md
- quick-start/index.html
- user-guide/installation/index.html
In response to your suggestion https://github.com/paulbutcher/ScalaMock/issues/43
> Set version 3.2.2 in quickstart and installation pages

- _user_guide/020_integration.md
To add an example of AsyncMockFactory in the User Guide.
There were no existing documentation for AsyncMockFactory.
#156
> Documentation for AsyncMockFactory

- .gitignore
- .travis.yml
- bintray.sbt
- build.sbt
- project/plugins.sbt
none
enables publishing snapshots to Sonatype
> publish to sonatype instead of bintray

- build.sbt
> fixed publication settings

- examples/shared/src/main/scala/com/example/Controller.scala
- examples/shared/src/main/scala/com/example/Order.scala
- examples/shared/src/main/scala/com/example/Turtle.scala
- examples/shared/src/main/scala/com/example/Warehouse.scala
- examples/shared/src/test/scala/com/example/function/HigherOrderFunctionsTest.scala
- examples/shared/src/test/scala/com/example/function/mockitostyle/HigherOrderFunctionsTest.scala
- shared/src/main/scala/org/scalamock/MockFactoryBase.scala
- shared/src/main/scala/org/scalamock/handlers/Handlers.scala
- shared/src/main/scala/org/scalamock/scalatest/AsyncMockFactoryBase.scala
- shared/src/test/scala/com/paulbutcher/test/IsolatedSpec.scala
- shared/src/test/scala/com/paulbutcher/test/mock/MockFunctionTest.scala
- shared/src/test/scala/com/paulbutcher/test/mock/MockTest.scala
- shared/src/test/scala/com/paulbutcher/test/stub/StubFunctionTest.scala
Fixes procedure syntax
procedure syntax is deprecated and will be removed
https://github.com/scala/scala/pull/6325
> fix procedure syntax

- shared/src/main/scala/org/scalamock/matchers/ArgCapture.scala
- shared/src/main/scala/org/scalamock/matchers/Matchers.scala
- shared/src/test/scala/com/paulbutcher/test/matchers/ArgCaptureTest.scala
> added argument capturing. fixes #234

- _user_guide/070_advanced_topics.md
> documentation for #234

- project/plugins.sbt
latest sbt-sonatype
latest sbt-sonatype
latest sbt-sonatype
latest sbt-sonatype
> sbt-sonatype 2.3

- build.sbt
- shared/src/main/scala/org/scalamock/util/MacroUtils.scala
- shared/src/test/scala/com/paulbutcher/test/mock/MockTest.scala
> check types as well as name when looking for members of Object

- README.md
Update the readme for release 4.3.0
> Update for release 4.3.0

- examples/src/test/scala/com/example/ReallySimpleExampleTest.scala
Adds a new really simple example to get people started
> added greeter example

- project/plugins.sbt
> scala.js 1.4

- _user_guide/070_advanced_topics.md
N/A
To provide an example for scalamock beginners.
I was confusing when I tried to do this.
N/A
> Added how to mock 0-parameter and parameterless

- build.sbt
- publishing.sbt
update .sbt files to new syntax
> updating to new SBT syntax

- publishing.sbt
> replaced deprecated publishTo setting

- .github/workflows/release.yml
- .github/workflows/scala.yml
- build.sbt
Update java to 21. Since library has no specific java API, everything should be OK
> compile and publish with java 21

- shared/src/test/scala/com/paulbutcher/test/mock/MockTest.scala
> uncomment and fix test for issue #150

- shared/src/test/scala/com/paulbutcher/test/TestTrait.scala
- shared/src/test/scala/com/paulbutcher/test/mock/MockTest.scala
> added test for issue 131

- cats-effect/shared/src/main/scala/org/scalamock/stubs/CatsEffectStubs.scala
- core/shared/src/main/scala/org/scalamock/clazz/MockFunctionFinder.scala
- core/shared/src/main/scala/org/scalamock/clazz/Utils.scala
- core/shared/src/main/scala/org/scalamock/stubs/StubIO.scala
- core/shared/src/main/scala/org/scalamock/stubs/internal/StubMaker.scala
- zio/shared/src/main/scala/org/scalamock/stubs/ZIOStubs.scala
> refactoring; wrap NotImplementedError with effect

- README.md
- cats-effect/shared/src/main/scala/org/scalamock/stubs/CatsEffectStubs.scala
- cats-effect/shared/src/test/scala/tests/IOSpec.scala
- core/shared/src/main/scala/org/scalamock/clazz/Utils.scala
- core/shared/src/main/scala/org/scalamock/stubs/StubArgumentLog.scala
- core/shared/src/main/scala/org/scalamock/stubs/Stubs.scala
- core/shared/src/main/scala/org/scalamock/stubs/internal/CreatedStubs.scala
- core/shared/src/main/scala/org/scalamock/stubs/internal/StubMaker.scala
- core/shared/src/main/scala/org/scalamock/stubs/internal/constants.scala
- core/shared/src/test/scala/newapi/CallLogSpec.scala
- zio/shared/src/main/scala/org/scalamock/stubs/ZIOStubs.scala
- zio/shared/src/test/scala/tests/ZIOSpec.scala
- zio/shared/src/test/scala/tests/ZIOVerifySpec.scala
Implemented basic call log support for new API
> implement call log

- .clabot
Fixes #xxxx
What does this PR do?
Why did you take this approach?
Are there any relevant issues / PRs / mailing lists discussions?
> add cla-bot

- _user_guide/010_installation.md
- _user_guide/020_integration.md
- _user_guide/025_features.md
- _user_guide/030_mocking_style.md
- _user_guide/040_matching.md
- _user_guide/050_ordering.md
- _user_guide/061_sharing_scalatest.md
- _user_guide/062_sharing_specs2.md
- _user_guide/070_advanced_topics.md
- _user_guide/080_faq.md
- quick_start.md
Fixes #xxxx
What does this PR do?
Why did you take this approach?
Are there any relevant issues / PRs / mailing lists discussions?
> update documentation; add documetation for new experimental api

- _user_guide/020_integration.md
- _user_guide/040_matching.md
- _user_guide/050_ordering.md
- _user_guide/070_advanced_topics.md
- quick_start.md
Fixes #xxxx
What does this PR do?
Why did you take this approach?
Are there any relevant issues / PRs / mailing lists discussions?
> small docs fixes

- README.md
- cats-effect/shared/src/test/scala/tests/CEUserAuthServiceSpec.scala
- core/jvm/src/test/scala/newapi/UserAuthServiceSpec.scala
- zio/shared/src/test/scala/tests/ZIOUserAuthServiceSpec.scala
Fixes #xxxx
What does this PR do?
Why did you take this approach?
Are there any relevant issues / PRs / mailing lists discussions?
> add examples

- core/shared/src/main/scala/org/scalamock/clazz/Utils.scala
- core/shared/src/test/scala/com/paulbutcher/test/MockTestScala3.scala
> fix all parameter types related problems

- .github/workflows/scala.yml
- shared/src/main/scala-3/org/scalamock/clazz/MockMaker.scala
- shared/src/test/scala-3/com/paulbutcher/test/MockTestScala3.scala
> fix all scala 3 constructor parameter types related problems

- core/shared/src/main/scala/org/scalamock/clazz/Utils.scala
- core/shared/src/main/scala/org/scalamock/util/Defaultable.scala
- core/shared/src/test/scala/com/paulbutcher/test/MockTestScala3.scala
- core/shared/src/test/scala/com/paulbutcher/test/ThisTypeTrait.scala
> fix issue#209

- shared/src/main/scala-3/org/scalamock/clazz/MockMaker.scala
- shared/src/main/scala-3/org/scalamock/clazz/Utils.scala
- shared/src/test/scala-3/com/paulbutcher/test/MockTestScala3.scala
- shared/src/test/scala-3/com/paulbutcher/test/Scala3Spec.scala
- shared/src/test/scala-3/com/paulbutcher/test/ThisTypeTrait.scala
> fix methods returning this.type; issue#209
